// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package middleware.proto;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:middleware.proto.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.middleware.proto.Assignment assignment = 1;</code>
     * @return Whether the assignment field is set.
     */
    boolean hasAssignment();
    /**
     * <code>.middleware.proto.Assignment assignment = 1;</code>
     * @return The assignment.
     */
    middleware.proto.AssignmentOuterClass.Assignment getAssignment();
    /**
     * <code>.middleware.proto.Assignment assignment = 1;</code>
     */
    middleware.proto.AssignmentOuterClass.AssignmentOrBuilder getAssignmentOrBuilder();

    /**
     * <code>.middleware.proto.Request request = 2;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.middleware.proto.Request request = 2;</code>
     * @return The request.
     */
    middleware.proto.RequestOuterClass.Request getRequest();
    /**
     * <code>.middleware.proto.Request request = 2;</code>
     */
    middleware.proto.RequestOuterClass.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>.middleware.proto.Replication replication = 4;</code>
     * @return Whether the replication field is set.
     */
    boolean hasReplication();
    /**
     * <code>.middleware.proto.Replication replication = 4;</code>
     * @return The replication.
     */
    middleware.proto.ReplicationOuterClass.Replication getReplication();
    /**
     * <code>.middleware.proto.Replication replication = 4;</code>
     */
    middleware.proto.ReplicationOuterClass.ReplicationOrBuilder getReplicationOrBuilder();

    public middleware.proto.MessageOuterClass.Message.TypeCase getTypeCase();
  }
  /**
   * Protobuf type {@code middleware.proto.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:middleware.proto.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              middleware.proto.AssignmentOuterClass.Assignment.Builder subBuilder = null;
              if (typeCase_ == 1) {
                subBuilder = ((middleware.proto.AssignmentOuterClass.Assignment) type_).toBuilder();
              }
              type_ =
                  input.readMessage(middleware.proto.AssignmentOuterClass.Assignment.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((middleware.proto.AssignmentOuterClass.Assignment) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 1;
              break;
            }
            case 18: {
              middleware.proto.RequestOuterClass.Request.Builder subBuilder = null;
              if (typeCase_ == 2) {
                subBuilder = ((middleware.proto.RequestOuterClass.Request) type_).toBuilder();
              }
              type_ =
                  input.readMessage(middleware.proto.RequestOuterClass.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((middleware.proto.RequestOuterClass.Request) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 2;
              break;
            }
            case 34: {
              middleware.proto.ReplicationOuterClass.Replication.Builder subBuilder = null;
              if (typeCase_ == 4) {
                subBuilder = ((middleware.proto.ReplicationOuterClass.Replication) type_).toBuilder();
              }
              type_ =
                  input.readMessage(middleware.proto.ReplicationOuterClass.Replication.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((middleware.proto.ReplicationOuterClass.Replication) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 4;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return middleware.proto.MessageOuterClass.internal_static_middleware_proto_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return middleware.proto.MessageOuterClass.internal_static_middleware_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              middleware.proto.MessageOuterClass.Message.class, middleware.proto.MessageOuterClass.Message.Builder.class);
    }

    private int typeCase_ = 0;
    private java.lang.Object type_;
    public enum TypeCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      ASSIGNMENT(1),
      REQUEST(2),
      REPLICATION(4),
      TYPE_NOT_SET(0);
      private final int value;
      private TypeCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static TypeCase forNumber(int value) {
        switch (value) {
          case 1: return ASSIGNMENT;
          case 2: return REQUEST;
          case 4: return REPLICATION;
          case 0: return TYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypeCase
    getTypeCase() {
      return TypeCase.forNumber(
          typeCase_);
    }

    public static final int ASSIGNMENT_FIELD_NUMBER = 1;
    /**
     * <code>.middleware.proto.Assignment assignment = 1;</code>
     * @return Whether the assignment field is set.
     */
    public boolean hasAssignment() {
      return typeCase_ == 1;
    }
    /**
     * <code>.middleware.proto.Assignment assignment = 1;</code>
     * @return The assignment.
     */
    public middleware.proto.AssignmentOuterClass.Assignment getAssignment() {
      if (typeCase_ == 1) {
         return (middleware.proto.AssignmentOuterClass.Assignment) type_;
      }
      return middleware.proto.AssignmentOuterClass.Assignment.getDefaultInstance();
    }
    /**
     * <code>.middleware.proto.Assignment assignment = 1;</code>
     */
    public middleware.proto.AssignmentOuterClass.AssignmentOrBuilder getAssignmentOrBuilder() {
      if (typeCase_ == 1) {
         return (middleware.proto.AssignmentOuterClass.Assignment) type_;
      }
      return middleware.proto.AssignmentOuterClass.Assignment.getDefaultInstance();
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    /**
     * <code>.middleware.proto.Request request = 2;</code>
     * @return Whether the request field is set.
     */
    public boolean hasRequest() {
      return typeCase_ == 2;
    }
    /**
     * <code>.middleware.proto.Request request = 2;</code>
     * @return The request.
     */
    public middleware.proto.RequestOuterClass.Request getRequest() {
      if (typeCase_ == 2) {
         return (middleware.proto.RequestOuterClass.Request) type_;
      }
      return middleware.proto.RequestOuterClass.Request.getDefaultInstance();
    }
    /**
     * <code>.middleware.proto.Request request = 2;</code>
     */
    public middleware.proto.RequestOuterClass.RequestOrBuilder getRequestOrBuilder() {
      if (typeCase_ == 2) {
         return (middleware.proto.RequestOuterClass.Request) type_;
      }
      return middleware.proto.RequestOuterClass.Request.getDefaultInstance();
    }

    public static final int REPLICATION_FIELD_NUMBER = 4;
    /**
     * <code>.middleware.proto.Replication replication = 4;</code>
     * @return Whether the replication field is set.
     */
    public boolean hasReplication() {
      return typeCase_ == 4;
    }
    /**
     * <code>.middleware.proto.Replication replication = 4;</code>
     * @return The replication.
     */
    public middleware.proto.ReplicationOuterClass.Replication getReplication() {
      if (typeCase_ == 4) {
         return (middleware.proto.ReplicationOuterClass.Replication) type_;
      }
      return middleware.proto.ReplicationOuterClass.Replication.getDefaultInstance();
    }
    /**
     * <code>.middleware.proto.Replication replication = 4;</code>
     */
    public middleware.proto.ReplicationOuterClass.ReplicationOrBuilder getReplicationOrBuilder() {
      if (typeCase_ == 4) {
         return (middleware.proto.ReplicationOuterClass.Replication) type_;
      }
      return middleware.proto.ReplicationOuterClass.Replication.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (typeCase_ == 1) {
        output.writeMessage(1, (middleware.proto.AssignmentOuterClass.Assignment) type_);
      }
      if (typeCase_ == 2) {
        output.writeMessage(2, (middleware.proto.RequestOuterClass.Request) type_);
      }
      if (typeCase_ == 4) {
        output.writeMessage(4, (middleware.proto.ReplicationOuterClass.Replication) type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (typeCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (middleware.proto.AssignmentOuterClass.Assignment) type_);
      }
      if (typeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (middleware.proto.RequestOuterClass.Request) type_);
      }
      if (typeCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (middleware.proto.ReplicationOuterClass.Replication) type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof middleware.proto.MessageOuterClass.Message)) {
        return super.equals(obj);
      }
      middleware.proto.MessageOuterClass.Message other = (middleware.proto.MessageOuterClass.Message) obj;

      if (!getTypeCase().equals(other.getTypeCase())) return false;
      switch (typeCase_) {
        case 1:
          if (!getAssignment()
              .equals(other.getAssignment())) return false;
          break;
        case 2:
          if (!getRequest()
              .equals(other.getRequest())) return false;
          break;
        case 4:
          if (!getReplication()
              .equals(other.getReplication())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (typeCase_) {
        case 1:
          hash = (37 * hash) + ASSIGNMENT_FIELD_NUMBER;
          hash = (53 * hash) + getAssignment().hashCode();
          break;
        case 2:
          hash = (37 * hash) + REQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getRequest().hashCode();
          break;
        case 4:
          hash = (37 * hash) + REPLICATION_FIELD_NUMBER;
          hash = (53 * hash) + getReplication().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static middleware.proto.MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static middleware.proto.MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static middleware.proto.MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static middleware.proto.MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static middleware.proto.MessageOuterClass.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static middleware.proto.MessageOuterClass.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static middleware.proto.MessageOuterClass.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static middleware.proto.MessageOuterClass.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static middleware.proto.MessageOuterClass.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static middleware.proto.MessageOuterClass.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static middleware.proto.MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static middleware.proto.MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(middleware.proto.MessageOuterClass.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code middleware.proto.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:middleware.proto.Message)
        middleware.proto.MessageOuterClass.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return middleware.proto.MessageOuterClass.internal_static_middleware_proto_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return middleware.proto.MessageOuterClass.internal_static_middleware_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                middleware.proto.MessageOuterClass.Message.class, middleware.proto.MessageOuterClass.Message.Builder.class);
      }

      // Construct using middleware.proto.MessageOuterClass.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        typeCase_ = 0;
        type_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return middleware.proto.MessageOuterClass.internal_static_middleware_proto_Message_descriptor;
      }

      @java.lang.Override
      public middleware.proto.MessageOuterClass.Message getDefaultInstanceForType() {
        return middleware.proto.MessageOuterClass.Message.getDefaultInstance();
      }

      @java.lang.Override
      public middleware.proto.MessageOuterClass.Message build() {
        middleware.proto.MessageOuterClass.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public middleware.proto.MessageOuterClass.Message buildPartial() {
        middleware.proto.MessageOuterClass.Message result = new middleware.proto.MessageOuterClass.Message(this);
        if (typeCase_ == 1) {
          if (assignmentBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = assignmentBuilder_.build();
          }
        }
        if (typeCase_ == 2) {
          if (requestBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = requestBuilder_.build();
          }
        }
        if (typeCase_ == 4) {
          if (replicationBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = replicationBuilder_.build();
          }
        }
        result.typeCase_ = typeCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof middleware.proto.MessageOuterClass.Message) {
          return mergeFrom((middleware.proto.MessageOuterClass.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(middleware.proto.MessageOuterClass.Message other) {
        if (other == middleware.proto.MessageOuterClass.Message.getDefaultInstance()) return this;
        switch (other.getTypeCase()) {
          case ASSIGNMENT: {
            mergeAssignment(other.getAssignment());
            break;
          }
          case REQUEST: {
            mergeRequest(other.getRequest());
            break;
          }
          case REPLICATION: {
            mergeReplication(other.getReplication());
            break;
          }
          case TYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        middleware.proto.MessageOuterClass.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (middleware.proto.MessageOuterClass.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int typeCase_ = 0;
      private java.lang.Object type_;
      public TypeCase
          getTypeCase() {
        return TypeCase.forNumber(
            typeCase_);
      }

      public Builder clearType() {
        typeCase_ = 0;
        type_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          middleware.proto.AssignmentOuterClass.Assignment, middleware.proto.AssignmentOuterClass.Assignment.Builder, middleware.proto.AssignmentOuterClass.AssignmentOrBuilder> assignmentBuilder_;
      /**
       * <code>.middleware.proto.Assignment assignment = 1;</code>
       * @return Whether the assignment field is set.
       */
      public boolean hasAssignment() {
        return typeCase_ == 1;
      }
      /**
       * <code>.middleware.proto.Assignment assignment = 1;</code>
       * @return The assignment.
       */
      public middleware.proto.AssignmentOuterClass.Assignment getAssignment() {
        if (assignmentBuilder_ == null) {
          if (typeCase_ == 1) {
            return (middleware.proto.AssignmentOuterClass.Assignment) type_;
          }
          return middleware.proto.AssignmentOuterClass.Assignment.getDefaultInstance();
        } else {
          if (typeCase_ == 1) {
            return assignmentBuilder_.getMessage();
          }
          return middleware.proto.AssignmentOuterClass.Assignment.getDefaultInstance();
        }
      }
      /**
       * <code>.middleware.proto.Assignment assignment = 1;</code>
       */
      public Builder setAssignment(middleware.proto.AssignmentOuterClass.Assignment value) {
        if (assignmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          assignmentBuilder_.setMessage(value);
        }
        typeCase_ = 1;
        return this;
      }
      /**
       * <code>.middleware.proto.Assignment assignment = 1;</code>
       */
      public Builder setAssignment(
          middleware.proto.AssignmentOuterClass.Assignment.Builder builderForValue) {
        if (assignmentBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          assignmentBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 1;
        return this;
      }
      /**
       * <code>.middleware.proto.Assignment assignment = 1;</code>
       */
      public Builder mergeAssignment(middleware.proto.AssignmentOuterClass.Assignment value) {
        if (assignmentBuilder_ == null) {
          if (typeCase_ == 1 &&
              type_ != middleware.proto.AssignmentOuterClass.Assignment.getDefaultInstance()) {
            type_ = middleware.proto.AssignmentOuterClass.Assignment.newBuilder((middleware.proto.AssignmentOuterClass.Assignment) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 1) {
            assignmentBuilder_.mergeFrom(value);
          }
          assignmentBuilder_.setMessage(value);
        }
        typeCase_ = 1;
        return this;
      }
      /**
       * <code>.middleware.proto.Assignment assignment = 1;</code>
       */
      public Builder clearAssignment() {
        if (assignmentBuilder_ == null) {
          if (typeCase_ == 1) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 1) {
            typeCase_ = 0;
            type_ = null;
          }
          assignmentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.middleware.proto.Assignment assignment = 1;</code>
       */
      public middleware.proto.AssignmentOuterClass.Assignment.Builder getAssignmentBuilder() {
        return getAssignmentFieldBuilder().getBuilder();
      }
      /**
       * <code>.middleware.proto.Assignment assignment = 1;</code>
       */
      public middleware.proto.AssignmentOuterClass.AssignmentOrBuilder getAssignmentOrBuilder() {
        if ((typeCase_ == 1) && (assignmentBuilder_ != null)) {
          return assignmentBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 1) {
            return (middleware.proto.AssignmentOuterClass.Assignment) type_;
          }
          return middleware.proto.AssignmentOuterClass.Assignment.getDefaultInstance();
        }
      }
      /**
       * <code>.middleware.proto.Assignment assignment = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          middleware.proto.AssignmentOuterClass.Assignment, middleware.proto.AssignmentOuterClass.Assignment.Builder, middleware.proto.AssignmentOuterClass.AssignmentOrBuilder> 
          getAssignmentFieldBuilder() {
        if (assignmentBuilder_ == null) {
          if (!(typeCase_ == 1)) {
            type_ = middleware.proto.AssignmentOuterClass.Assignment.getDefaultInstance();
          }
          assignmentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              middleware.proto.AssignmentOuterClass.Assignment, middleware.proto.AssignmentOuterClass.Assignment.Builder, middleware.proto.AssignmentOuterClass.AssignmentOrBuilder>(
                  (middleware.proto.AssignmentOuterClass.Assignment) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 1;
        onChanged();;
        return assignmentBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          middleware.proto.RequestOuterClass.Request, middleware.proto.RequestOuterClass.Request.Builder, middleware.proto.RequestOuterClass.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.middleware.proto.Request request = 2;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return typeCase_ == 2;
      }
      /**
       * <code>.middleware.proto.Request request = 2;</code>
       * @return The request.
       */
      public middleware.proto.RequestOuterClass.Request getRequest() {
        if (requestBuilder_ == null) {
          if (typeCase_ == 2) {
            return (middleware.proto.RequestOuterClass.Request) type_;
          }
          return middleware.proto.RequestOuterClass.Request.getDefaultInstance();
        } else {
          if (typeCase_ == 2) {
            return requestBuilder_.getMessage();
          }
          return middleware.proto.RequestOuterClass.Request.getDefaultInstance();
        }
      }
      /**
       * <code>.middleware.proto.Request request = 2;</code>
       */
      public Builder setRequest(middleware.proto.RequestOuterClass.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>.middleware.proto.Request request = 2;</code>
       */
      public Builder setRequest(
          middleware.proto.RequestOuterClass.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>.middleware.proto.Request request = 2;</code>
       */
      public Builder mergeRequest(middleware.proto.RequestOuterClass.Request value) {
        if (requestBuilder_ == null) {
          if (typeCase_ == 2 &&
              type_ != middleware.proto.RequestOuterClass.Request.getDefaultInstance()) {
            type_ = middleware.proto.RequestOuterClass.Request.newBuilder((middleware.proto.RequestOuterClass.Request) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 2) {
            requestBuilder_.mergeFrom(value);
          }
          requestBuilder_.setMessage(value);
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>.middleware.proto.Request request = 2;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
          }
          requestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.middleware.proto.Request request = 2;</code>
       */
      public middleware.proto.RequestOuterClass.Request.Builder getRequestBuilder() {
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.middleware.proto.Request request = 2;</code>
       */
      public middleware.proto.RequestOuterClass.RequestOrBuilder getRequestOrBuilder() {
        if ((typeCase_ == 2) && (requestBuilder_ != null)) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 2) {
            return (middleware.proto.RequestOuterClass.Request) type_;
          }
          return middleware.proto.RequestOuterClass.Request.getDefaultInstance();
        }
      }
      /**
       * <code>.middleware.proto.Request request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          middleware.proto.RequestOuterClass.Request, middleware.proto.RequestOuterClass.Request.Builder, middleware.proto.RequestOuterClass.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          if (!(typeCase_ == 2)) {
            type_ = middleware.proto.RequestOuterClass.Request.getDefaultInstance();
          }
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              middleware.proto.RequestOuterClass.Request, middleware.proto.RequestOuterClass.Request.Builder, middleware.proto.RequestOuterClass.RequestOrBuilder>(
                  (middleware.proto.RequestOuterClass.Request) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 2;
        onChanged();;
        return requestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          middleware.proto.ReplicationOuterClass.Replication, middleware.proto.ReplicationOuterClass.Replication.Builder, middleware.proto.ReplicationOuterClass.ReplicationOrBuilder> replicationBuilder_;
      /**
       * <code>.middleware.proto.Replication replication = 4;</code>
       * @return Whether the replication field is set.
       */
      public boolean hasReplication() {
        return typeCase_ == 4;
      }
      /**
       * <code>.middleware.proto.Replication replication = 4;</code>
       * @return The replication.
       */
      public middleware.proto.ReplicationOuterClass.Replication getReplication() {
        if (replicationBuilder_ == null) {
          if (typeCase_ == 4) {
            return (middleware.proto.ReplicationOuterClass.Replication) type_;
          }
          return middleware.proto.ReplicationOuterClass.Replication.getDefaultInstance();
        } else {
          if (typeCase_ == 4) {
            return replicationBuilder_.getMessage();
          }
          return middleware.proto.ReplicationOuterClass.Replication.getDefaultInstance();
        }
      }
      /**
       * <code>.middleware.proto.Replication replication = 4;</code>
       */
      public Builder setReplication(middleware.proto.ReplicationOuterClass.Replication value) {
        if (replicationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          replicationBuilder_.setMessage(value);
        }
        typeCase_ = 4;
        return this;
      }
      /**
       * <code>.middleware.proto.Replication replication = 4;</code>
       */
      public Builder setReplication(
          middleware.proto.ReplicationOuterClass.Replication.Builder builderForValue) {
        if (replicationBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          replicationBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 4;
        return this;
      }
      /**
       * <code>.middleware.proto.Replication replication = 4;</code>
       */
      public Builder mergeReplication(middleware.proto.ReplicationOuterClass.Replication value) {
        if (replicationBuilder_ == null) {
          if (typeCase_ == 4 &&
              type_ != middleware.proto.ReplicationOuterClass.Replication.getDefaultInstance()) {
            type_ = middleware.proto.ReplicationOuterClass.Replication.newBuilder((middleware.proto.ReplicationOuterClass.Replication) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 4) {
            replicationBuilder_.mergeFrom(value);
          }
          replicationBuilder_.setMessage(value);
        }
        typeCase_ = 4;
        return this;
      }
      /**
       * <code>.middleware.proto.Replication replication = 4;</code>
       */
      public Builder clearReplication() {
        if (replicationBuilder_ == null) {
          if (typeCase_ == 4) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 4) {
            typeCase_ = 0;
            type_ = null;
          }
          replicationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.middleware.proto.Replication replication = 4;</code>
       */
      public middleware.proto.ReplicationOuterClass.Replication.Builder getReplicationBuilder() {
        return getReplicationFieldBuilder().getBuilder();
      }
      /**
       * <code>.middleware.proto.Replication replication = 4;</code>
       */
      public middleware.proto.ReplicationOuterClass.ReplicationOrBuilder getReplicationOrBuilder() {
        if ((typeCase_ == 4) && (replicationBuilder_ != null)) {
          return replicationBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 4) {
            return (middleware.proto.ReplicationOuterClass.Replication) type_;
          }
          return middleware.proto.ReplicationOuterClass.Replication.getDefaultInstance();
        }
      }
      /**
       * <code>.middleware.proto.Replication replication = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          middleware.proto.ReplicationOuterClass.Replication, middleware.proto.ReplicationOuterClass.Replication.Builder, middleware.proto.ReplicationOuterClass.ReplicationOrBuilder> 
          getReplicationFieldBuilder() {
        if (replicationBuilder_ == null) {
          if (!(typeCase_ == 4)) {
            type_ = middleware.proto.ReplicationOuterClass.Replication.getDefaultInstance();
          }
          replicationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              middleware.proto.ReplicationOuterClass.Replication, middleware.proto.ReplicationOuterClass.Replication.Builder, middleware.proto.ReplicationOuterClass.ReplicationOrBuilder>(
                  (middleware.proto.ReplicationOuterClass.Replication) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 4;
        onChanged();;
        return replicationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:middleware.proto.Message)
    }

    // @@protoc_insertion_point(class_scope:middleware.proto.Message)
    private static final middleware.proto.MessageOuterClass.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new middleware.proto.MessageOuterClass.Message();
    }

    public static middleware.proto.MessageOuterClass.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public middleware.proto.MessageOuterClass.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_middleware_proto_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_middleware_proto_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\020middleware.proto\032\033assig" +
      "nment/assignment.proto\032\025request/request." +
      "proto\032\035replication/replication.proto\"\251\001\n" +
      "\007Message\0222\n\nassignment\030\001 \001(\0132\034.middlewar" +
      "e.proto.AssignmentH\000\022,\n\007request\030\002 \001(\0132\031." +
      "middleware.proto.RequestH\000\0224\n\013replicatio" +
      "n\030\004 \001(\0132\035.middleware.proto.ReplicationH\000" +
      "B\006\n\004typeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          middleware.proto.AssignmentOuterClass.getDescriptor(),
          middleware.proto.RequestOuterClass.getDescriptor(),
          middleware.proto.ReplicationOuterClass.getDescriptor(),
        });
    internal_static_middleware_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_middleware_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_middleware_proto_Message_descriptor,
        new java.lang.String[] { "Assignment", "Request", "Replication", "Type", });
    middleware.proto.AssignmentOuterClass.getDescriptor();
    middleware.proto.RequestOuterClass.getDescriptor();
    middleware.proto.ReplicationOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
