// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recovery.proto

package middleware.proto;

public final class RecoveryOuterClass {
  private RecoveryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecoveryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:middleware.proto.Recovery)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
     */
    java.util.List<middleware.proto.RecoveryOuterClass.Recovery.Line> 
        getLinesList();
    /**
     * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
     */
    middleware.proto.RecoveryOuterClass.Recovery.Line getLines(int index);
    /**
     * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
     */
    int getLinesCount();
    /**
     * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
     */
    java.util.List<? extends middleware.proto.RecoveryOuterClass.Recovery.LineOrBuilder> 
        getLinesOrBuilderList();
    /**
     * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
     */
    middleware.proto.RecoveryOuterClass.Recovery.LineOrBuilder getLinesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code middleware.proto.Recovery}
   */
  public  static final class Recovery extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:middleware.proto.Recovery)
      RecoveryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Recovery.newBuilder() to construct.
    private Recovery(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Recovery() {
      lines_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Recovery();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Recovery(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                lines_ = new java.util.ArrayList<middleware.proto.RecoveryOuterClass.Recovery.Line>();
                mutable_bitField0_ |= 0x00000001;
              }
              lines_.add(
                  input.readMessage(middleware.proto.RecoveryOuterClass.Recovery.Line.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          lines_ = java.util.Collections.unmodifiableList(lines_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return middleware.proto.RecoveryOuterClass.internal_static_middleware_proto_Recovery_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return middleware.proto.RecoveryOuterClass.internal_static_middleware_proto_Recovery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              middleware.proto.RecoveryOuterClass.Recovery.class, middleware.proto.RecoveryOuterClass.Recovery.Builder.class);
    }

    public interface LineOrBuilder extends
        // @@protoc_insertion_point(interface_extends:middleware.proto.Recovery.Line)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 number = 1;</code>
       * @return The number.
       */
      int getNumber();

      /**
       * <code>string data = 2;</code>
       * @return The data.
       */
      java.lang.String getData();
      /**
       * <code>string data = 2;</code>
       * @return The bytes for data.
       */
      com.google.protobuf.ByteString
          getDataBytes();
    }
    /**
     * Protobuf type {@code middleware.proto.Recovery.Line}
     */
    public  static final class Line extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:middleware.proto.Recovery.Line)
        LineOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Line.newBuilder() to construct.
      private Line(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Line() {
        data_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Line();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Line(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                number_ = input.readInt32();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                data_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return middleware.proto.RecoveryOuterClass.internal_static_middleware_proto_Recovery_Line_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return middleware.proto.RecoveryOuterClass.internal_static_middleware_proto_Recovery_Line_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                middleware.proto.RecoveryOuterClass.Recovery.Line.class, middleware.proto.RecoveryOuterClass.Recovery.Line.Builder.class);
      }

      public static final int NUMBER_FIELD_NUMBER = 1;
      private int number_;
      /**
       * <code>int32 number = 1;</code>
       * @return The number.
       */
      public int getNumber() {
        return number_;
      }

      public static final int DATA_FIELD_NUMBER = 2;
      private volatile java.lang.Object data_;
      /**
       * <code>string data = 2;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        }
      }
      /**
       * <code>string data = 2;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (number_ != 0) {
          output.writeInt32(1, number_);
        }
        if (!getDataBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (number_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, number_);
        }
        if (!getDataBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof middleware.proto.RecoveryOuterClass.Recovery.Line)) {
          return super.equals(obj);
        }
        middleware.proto.RecoveryOuterClass.Recovery.Line other = (middleware.proto.RecoveryOuterClass.Recovery.Line) obj;

        if (getNumber()
            != other.getNumber()) return false;
        if (!getData()
            .equals(other.getData())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber();
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static middleware.proto.RecoveryOuterClass.Recovery.Line parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static middleware.proto.RecoveryOuterClass.Recovery.Line parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static middleware.proto.RecoveryOuterClass.Recovery.Line parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static middleware.proto.RecoveryOuterClass.Recovery.Line parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static middleware.proto.RecoveryOuterClass.Recovery.Line parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static middleware.proto.RecoveryOuterClass.Recovery.Line parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static middleware.proto.RecoveryOuterClass.Recovery.Line parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static middleware.proto.RecoveryOuterClass.Recovery.Line parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static middleware.proto.RecoveryOuterClass.Recovery.Line parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static middleware.proto.RecoveryOuterClass.Recovery.Line parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static middleware.proto.RecoveryOuterClass.Recovery.Line parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static middleware.proto.RecoveryOuterClass.Recovery.Line parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(middleware.proto.RecoveryOuterClass.Recovery.Line prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code middleware.proto.Recovery.Line}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:middleware.proto.Recovery.Line)
          middleware.proto.RecoveryOuterClass.Recovery.LineOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return middleware.proto.RecoveryOuterClass.internal_static_middleware_proto_Recovery_Line_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return middleware.proto.RecoveryOuterClass.internal_static_middleware_proto_Recovery_Line_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  middleware.proto.RecoveryOuterClass.Recovery.Line.class, middleware.proto.RecoveryOuterClass.Recovery.Line.Builder.class);
        }

        // Construct using middleware.proto.RecoveryOuterClass.Recovery.Line.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          number_ = 0;

          data_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return middleware.proto.RecoveryOuterClass.internal_static_middleware_proto_Recovery_Line_descriptor;
        }

        @java.lang.Override
        public middleware.proto.RecoveryOuterClass.Recovery.Line getDefaultInstanceForType() {
          return middleware.proto.RecoveryOuterClass.Recovery.Line.getDefaultInstance();
        }

        @java.lang.Override
        public middleware.proto.RecoveryOuterClass.Recovery.Line build() {
          middleware.proto.RecoveryOuterClass.Recovery.Line result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public middleware.proto.RecoveryOuterClass.Recovery.Line buildPartial() {
          middleware.proto.RecoveryOuterClass.Recovery.Line result = new middleware.proto.RecoveryOuterClass.Recovery.Line(this);
          result.number_ = number_;
          result.data_ = data_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof middleware.proto.RecoveryOuterClass.Recovery.Line) {
            return mergeFrom((middleware.proto.RecoveryOuterClass.Recovery.Line)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(middleware.proto.RecoveryOuterClass.Recovery.Line other) {
          if (other == middleware.proto.RecoveryOuterClass.Recovery.Line.getDefaultInstance()) return this;
          if (other.getNumber() != 0) {
            setNumber(other.getNumber());
          }
          if (!other.getData().isEmpty()) {
            data_ = other.data_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          middleware.proto.RecoveryOuterClass.Recovery.Line parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (middleware.proto.RecoveryOuterClass.Recovery.Line) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int number_ ;
        /**
         * <code>int32 number = 1;</code>
         * @return The number.
         */
        public int getNumber() {
          return number_;
        }
        /**
         * <code>int32 number = 1;</code>
         * @param value The number to set.
         * @return This builder for chaining.
         */
        public Builder setNumber(int value) {
          
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 number = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearNumber() {
          
          number_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object data_ = "";
        /**
         * <code>string data = 2;</code>
         * @return The data.
         */
        public java.lang.String getData() {
          java.lang.Object ref = data_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            data_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string data = 2;</code>
         * @return The bytes for data.
         */
        public com.google.protobuf.ByteString
            getDataBytes() {
          java.lang.Object ref = data_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            data_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string data = 2;</code>
         * @param value The data to set.
         * @return This builder for chaining.
         */
        public Builder setData(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string data = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearData() {
          
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }
        /**
         * <code>string data = 2;</code>
         * @param value The bytes for data to set.
         * @return This builder for chaining.
         */
        public Builder setDataBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          data_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:middleware.proto.Recovery.Line)
      }

      // @@protoc_insertion_point(class_scope:middleware.proto.Recovery.Line)
      private static final middleware.proto.RecoveryOuterClass.Recovery.Line DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new middleware.proto.RecoveryOuterClass.Recovery.Line();
      }

      public static middleware.proto.RecoveryOuterClass.Recovery.Line getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Line>
          PARSER = new com.google.protobuf.AbstractParser<Line>() {
        @java.lang.Override
        public Line parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Line(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Line> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Line> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public middleware.proto.RecoveryOuterClass.Recovery.Line getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int LINES_FIELD_NUMBER = 1;
    private java.util.List<middleware.proto.RecoveryOuterClass.Recovery.Line> lines_;
    /**
     * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
     */
    public java.util.List<middleware.proto.RecoveryOuterClass.Recovery.Line> getLinesList() {
      return lines_;
    }
    /**
     * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
     */
    public java.util.List<? extends middleware.proto.RecoveryOuterClass.Recovery.LineOrBuilder> 
        getLinesOrBuilderList() {
      return lines_;
    }
    /**
     * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
     */
    public int getLinesCount() {
      return lines_.size();
    }
    /**
     * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
     */
    public middleware.proto.RecoveryOuterClass.Recovery.Line getLines(int index) {
      return lines_.get(index);
    }
    /**
     * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
     */
    public middleware.proto.RecoveryOuterClass.Recovery.LineOrBuilder getLinesOrBuilder(
        int index) {
      return lines_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < lines_.size(); i++) {
        output.writeMessage(1, lines_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < lines_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, lines_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof middleware.proto.RecoveryOuterClass.Recovery)) {
        return super.equals(obj);
      }
      middleware.proto.RecoveryOuterClass.Recovery other = (middleware.proto.RecoveryOuterClass.Recovery) obj;

      if (!getLinesList()
          .equals(other.getLinesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLinesCount() > 0) {
        hash = (37 * hash) + LINES_FIELD_NUMBER;
        hash = (53 * hash) + getLinesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static middleware.proto.RecoveryOuterClass.Recovery parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static middleware.proto.RecoveryOuterClass.Recovery parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static middleware.proto.RecoveryOuterClass.Recovery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static middleware.proto.RecoveryOuterClass.Recovery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static middleware.proto.RecoveryOuterClass.Recovery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static middleware.proto.RecoveryOuterClass.Recovery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static middleware.proto.RecoveryOuterClass.Recovery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static middleware.proto.RecoveryOuterClass.Recovery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static middleware.proto.RecoveryOuterClass.Recovery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static middleware.proto.RecoveryOuterClass.Recovery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static middleware.proto.RecoveryOuterClass.Recovery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static middleware.proto.RecoveryOuterClass.Recovery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(middleware.proto.RecoveryOuterClass.Recovery prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code middleware.proto.Recovery}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:middleware.proto.Recovery)
        middleware.proto.RecoveryOuterClass.RecoveryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return middleware.proto.RecoveryOuterClass.internal_static_middleware_proto_Recovery_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return middleware.proto.RecoveryOuterClass.internal_static_middleware_proto_Recovery_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                middleware.proto.RecoveryOuterClass.Recovery.class, middleware.proto.RecoveryOuterClass.Recovery.Builder.class);
      }

      // Construct using middleware.proto.RecoveryOuterClass.Recovery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLinesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (linesBuilder_ == null) {
          lines_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          linesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return middleware.proto.RecoveryOuterClass.internal_static_middleware_proto_Recovery_descriptor;
      }

      @java.lang.Override
      public middleware.proto.RecoveryOuterClass.Recovery getDefaultInstanceForType() {
        return middleware.proto.RecoveryOuterClass.Recovery.getDefaultInstance();
      }

      @java.lang.Override
      public middleware.proto.RecoveryOuterClass.Recovery build() {
        middleware.proto.RecoveryOuterClass.Recovery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public middleware.proto.RecoveryOuterClass.Recovery buildPartial() {
        middleware.proto.RecoveryOuterClass.Recovery result = new middleware.proto.RecoveryOuterClass.Recovery(this);
        int from_bitField0_ = bitField0_;
        if (linesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            lines_ = java.util.Collections.unmodifiableList(lines_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.lines_ = lines_;
        } else {
          result.lines_ = linesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof middleware.proto.RecoveryOuterClass.Recovery) {
          return mergeFrom((middleware.proto.RecoveryOuterClass.Recovery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(middleware.proto.RecoveryOuterClass.Recovery other) {
        if (other == middleware.proto.RecoveryOuterClass.Recovery.getDefaultInstance()) return this;
        if (linesBuilder_ == null) {
          if (!other.lines_.isEmpty()) {
            if (lines_.isEmpty()) {
              lines_ = other.lines_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLinesIsMutable();
              lines_.addAll(other.lines_);
            }
            onChanged();
          }
        } else {
          if (!other.lines_.isEmpty()) {
            if (linesBuilder_.isEmpty()) {
              linesBuilder_.dispose();
              linesBuilder_ = null;
              lines_ = other.lines_;
              bitField0_ = (bitField0_ & ~0x00000001);
              linesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLinesFieldBuilder() : null;
            } else {
              linesBuilder_.addAllMessages(other.lines_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        middleware.proto.RecoveryOuterClass.Recovery parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (middleware.proto.RecoveryOuterClass.Recovery) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<middleware.proto.RecoveryOuterClass.Recovery.Line> lines_ =
        java.util.Collections.emptyList();
      private void ensureLinesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          lines_ = new java.util.ArrayList<middleware.proto.RecoveryOuterClass.Recovery.Line>(lines_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          middleware.proto.RecoveryOuterClass.Recovery.Line, middleware.proto.RecoveryOuterClass.Recovery.Line.Builder, middleware.proto.RecoveryOuterClass.Recovery.LineOrBuilder> linesBuilder_;

      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public java.util.List<middleware.proto.RecoveryOuterClass.Recovery.Line> getLinesList() {
        if (linesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(lines_);
        } else {
          return linesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public int getLinesCount() {
        if (linesBuilder_ == null) {
          return lines_.size();
        } else {
          return linesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public middleware.proto.RecoveryOuterClass.Recovery.Line getLines(int index) {
        if (linesBuilder_ == null) {
          return lines_.get(index);
        } else {
          return linesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public Builder setLines(
          int index, middleware.proto.RecoveryOuterClass.Recovery.Line value) {
        if (linesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinesIsMutable();
          lines_.set(index, value);
          onChanged();
        } else {
          linesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public Builder setLines(
          int index, middleware.proto.RecoveryOuterClass.Recovery.Line.Builder builderForValue) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.set(index, builderForValue.build());
          onChanged();
        } else {
          linesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public Builder addLines(middleware.proto.RecoveryOuterClass.Recovery.Line value) {
        if (linesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinesIsMutable();
          lines_.add(value);
          onChanged();
        } else {
          linesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public Builder addLines(
          int index, middleware.proto.RecoveryOuterClass.Recovery.Line value) {
        if (linesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinesIsMutable();
          lines_.add(index, value);
          onChanged();
        } else {
          linesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public Builder addLines(
          middleware.proto.RecoveryOuterClass.Recovery.Line.Builder builderForValue) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.add(builderForValue.build());
          onChanged();
        } else {
          linesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public Builder addLines(
          int index, middleware.proto.RecoveryOuterClass.Recovery.Line.Builder builderForValue) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.add(index, builderForValue.build());
          onChanged();
        } else {
          linesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public Builder addAllLines(
          java.lang.Iterable<? extends middleware.proto.RecoveryOuterClass.Recovery.Line> values) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, lines_);
          onChanged();
        } else {
          linesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public Builder clearLines() {
        if (linesBuilder_ == null) {
          lines_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          linesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public Builder removeLines(int index) {
        if (linesBuilder_ == null) {
          ensureLinesIsMutable();
          lines_.remove(index);
          onChanged();
        } else {
          linesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public middleware.proto.RecoveryOuterClass.Recovery.Line.Builder getLinesBuilder(
          int index) {
        return getLinesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public middleware.proto.RecoveryOuterClass.Recovery.LineOrBuilder getLinesOrBuilder(
          int index) {
        if (linesBuilder_ == null) {
          return lines_.get(index);  } else {
          return linesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public java.util.List<? extends middleware.proto.RecoveryOuterClass.Recovery.LineOrBuilder> 
           getLinesOrBuilderList() {
        if (linesBuilder_ != null) {
          return linesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(lines_);
        }
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public middleware.proto.RecoveryOuterClass.Recovery.Line.Builder addLinesBuilder() {
        return getLinesFieldBuilder().addBuilder(
            middleware.proto.RecoveryOuterClass.Recovery.Line.getDefaultInstance());
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public middleware.proto.RecoveryOuterClass.Recovery.Line.Builder addLinesBuilder(
          int index) {
        return getLinesFieldBuilder().addBuilder(
            index, middleware.proto.RecoveryOuterClass.Recovery.Line.getDefaultInstance());
      }
      /**
       * <code>repeated .middleware.proto.Recovery.Line lines = 1;</code>
       */
      public java.util.List<middleware.proto.RecoveryOuterClass.Recovery.Line.Builder> 
           getLinesBuilderList() {
        return getLinesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          middleware.proto.RecoveryOuterClass.Recovery.Line, middleware.proto.RecoveryOuterClass.Recovery.Line.Builder, middleware.proto.RecoveryOuterClass.Recovery.LineOrBuilder> 
          getLinesFieldBuilder() {
        if (linesBuilder_ == null) {
          linesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              middleware.proto.RecoveryOuterClass.Recovery.Line, middleware.proto.RecoveryOuterClass.Recovery.Line.Builder, middleware.proto.RecoveryOuterClass.Recovery.LineOrBuilder>(
                  lines_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          lines_ = null;
        }
        return linesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:middleware.proto.Recovery)
    }

    // @@protoc_insertion_point(class_scope:middleware.proto.Recovery)
    private static final middleware.proto.RecoveryOuterClass.Recovery DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new middleware.proto.RecoveryOuterClass.Recovery();
    }

    public static middleware.proto.RecoveryOuterClass.Recovery getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Recovery>
        PARSER = new com.google.protobuf.AbstractParser<Recovery>() {
      @java.lang.Override
      public Recovery parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Recovery(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Recovery> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Recovery> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public middleware.proto.RecoveryOuterClass.Recovery getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_middleware_proto_Recovery_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_middleware_proto_Recovery_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_middleware_proto_Recovery_Line_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_middleware_proto_Recovery_Line_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016recovery.proto\022\020middleware.proto\"`\n\010Re" +
      "covery\022.\n\005lines\030\001 \003(\0132\037.middleware.proto" +
      ".Recovery.Line\032$\n\004Line\022\016\n\006number\030\001 \001(\005\022\014" +
      "\n\004data\030\002 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_middleware_proto_Recovery_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_middleware_proto_Recovery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_middleware_proto_Recovery_descriptor,
        new java.lang.String[] { "Lines", });
    internal_static_middleware_proto_Recovery_Line_descriptor =
      internal_static_middleware_proto_Recovery_descriptor.getNestedTypes().get(0);
    internal_static_middleware_proto_Recovery_Line_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_middleware_proto_Recovery_Line_descriptor,
        new java.lang.String[] { "Number", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
